#!/bin/bash

docker-machine create --driver virtualbox dev
eval $(docker-machine env dev)
touch creds

rm -rf ./game/app/app/_sharedClientSide
rm -rf ./login/app/app/js/_sharedClientSide
rm -rf ./game/app/_sharedServerSide
rm -rf ./login/app/_sharedServerSide
rm -rf ./login/app/app/public

mkdir ./game/app/app/_sharedClientSide  
mkdir ./login/app/app/js/_sharedClientSide  
mkdir ./game/app/_sharedServerSide  
mkdir ./login/app/_sharedServerSide  
mkdir ./login/app/app/public

cp -a ./common/sharedClientSide/. ./game/app/app/_sharedClientSide 
cp -a ./common/sharedClientSide/. ./login/app/app/js/_sharedClientSide 
cp -a ./common/sharedServerSide/. ./game/app/_sharedServerSide
cp -a ./common/sharedServerSide/. ./login/app/_sharedServerSide 
cp -a ./common/sharedClientSide/. ./login/app/app/public/

echo "SERVER_REGISTRATION_HOST=$(docker-machine ip dev)" > ip
echo "HOST=$(docker-machine ip dev)" >> ip

# Stop and remove any old containers
docker-compose -f docker-compose.dev.yml stop
docker-compose -f docker-compose.dev.yml rm -f
docker-compose -f docker-compose.dev.yml build
docker-compose -f docker-compose.dev.yml up